CREATE TABLE IF NOT EXISTS nation (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE,
	alternative_name VARCHAR(255),
	flag_filename VARCHAR(255),
	alternative_flag_filename VARCHAR(255),
	parent_nation_id INT,
	nation_type_id INT,
	FOREIGN KEY (parent_nation_id) REFERENCES nation(id),
	FOREIGN KEY (nation_type_id) REFERENCES group_type(id)
);

ALTER TABLE nation
	ADD COLUMN alternative_flag_filename VARCHAR(255);

INSERT INTO nation (name, flag_filename, nation_type_id)
VALUES ('Great Britain', 'Great_Britain.png', 6);

INSERT INTO nation (name, flag_filename, nation_type_id)
VALUES ('Afghanistan', 'Afghanistan.png', 6), ('Albania', 'Albania.png', 6), ('Algeria', 'Algeria.png', 6), ('American Samoa', 'American_Samoa.png', 7),
	('Andorra', 'Andorra.png', 6), ('Angola', 'Angola.png', 6), ('Anguilla', 'Anguilla.png', 7), ('Antigua and Barbuda', 'Antigua_and_Barbuda.png', 6),
	('Argentina', 'Argentina.png', 6), ('Armenia', 'Armenia.png', 6), ('Aruba', 'Aruba.png', 6), ('Australia', 'Australia.png', 6),
	('Austria', 'Austria.png', 6), ('Azerbaijan', 'Azerbaijan.png', 6), ('Bahamas', 'Bahamas.png', 6), ('Bahrain', 'Bahrain.png', 6),
	('Bangladesh', 'Bangladesh.png', 6), ('Barbados', 'Barbados.png', 6), ('Belarus', 'Belarus.png', 6), ('Belgium', 'Belgium.png', 6),
	('Belize', 'Belize.png', 6), ('Benin', 'Benin.png', 6), ('Bermuda', 'Bermuda.png', 6), ('Bhutan', 'Bhutan.png', 6),
	('Bolivia', 'Bolivia.png', 6), ('Bosnia and Herzegovina', 'Bosnia_and_Herzegovina.png', 6), ('Botswana', 'Botswana.png', 6), ('Brazil', 'Brazil.png', 6),
	('British Virgin Islands', 'British_Virgin_Islands.png', 7), ('Brunei Darussalam', 'Brunei_Darussalam.png', 6), ('Bulgaria', 'Bulgaria.png', 6), ('Burkina Faso', 'Burkina_Faso.png', 6),
	('Burundi', 'Burundi.png', 6), ('Cambodia', 'Cambodia.png', 6), ('Cameroon', 'Cameroon.png', 6), ('Canada', 'Canada.png', 6),
	('Cape Verde Islands', 'Cape_Verde_Islands.png', 6), ('Cayman Islands', 'Cayman_Islands.png', 7), ('Central African Republic', 'Central_African_Republic.png', 6), ('Chad', 'Chad.png', 6),
	('Chile', 'Chile.png', 6), ('China PR', 'China_PR.png', 6), ('Chinese Taipei', 'Chinese_Taipei.png', 6), ('Colombia', 'Colombia.png', 6),
	('Comoros', 'Comoros.png', 6), ('Congo', 'Congo.png', 6), ('Congo DR', 'Congo_DR.png', 6), ('Cook Islands', 'Cook_Islands.png', 6),
	('Costa Rica', 'Costa_Rica.png', 6), ('Côte d''Ivoire', 'Côte d''Ivoire.png', 6), ('Croatia', 'Croatia.png', 6), ('Cuba', 'Cuba.png', 6),
	('Curaçao', 'Curaçao.png', 6), ('Cyprus', 'Cyprus.png', 6), ('Czech Republic', 'Czech_Republic.png', 6), ('Denmark', 'Denmark.png', 6),
	('Djibouti', 'Djibouti.png', 6), ('Dominica', 'Dominica.png', 6), ('Dominican Republic', 'Dominican_Republic.png', 6), ('Ecuador', 'Ecuador.png', 6),
	('Egypt', 'Egypt.png', 6), ('El Salvador', 'El_Salvador.png', 6), ('England', 'England.png', 6), ('Equatorial Guinea', 'Equatorial_Guinea.png', 6),
	('Eritrea', 'Eritrea.png', 6), ('Estonia', 'Estonia.png', 6), ('Ethiopia', 'Ethiopia.png', 6), ('Faroe Islands', 'Faroe Islands.png', 6),
	('Fiji', 'Fiji.png', 6), ('Finland', 'Finland.png', 6), ('France', 'France.png', 6), ('FYR Macedonia', 'FYR_Macedonia.png', 6),
	('Gabon', 'Gabon.png', 6), ('Gambia', 'Gambia.png', 6), ('Georgia', 'Georgia.png', 6), ('Germany', 'Germany.png', 6),
	('Ghana', 'Ghana.png', 6), ('Gibraltar', 'Gibraltar.png', 7), ('Greece', 'Greece.png', 6), ('Grenada', 'Grenada.png', 6),
	('Guam', 'Guam.png', 6), ('Guatemala', 'Guatemala.png', 6), ('Guinea', 'Guinea.png', 6), ('Guinea-Bissau', 'Guinea-Bissau.png', 6),
	('Guyana', 'Guyana.png', 6), ('Haiti', 'Haiti.png', 6), ('Honduras', 'Honduras.png', 6), ('Hong Kong', 'Hong_Kong.png', 7),
	('Hungary', 'Hungary.png', 6), ('Iceland', 'Iceland.png', 6), ('India', 'India.png', 6), ('Indonesia', 'Indonesia.png', 6),
	('Iran', 'Iran.png', 6), ('Iraq', 'Iraq.png', 6), ('Israel', 'Israel.png', 6), ('Italy', 'Italy.png', 6),
	('Jamaica', 'Jamaica.png', 6), ('Japan', 'Japan.png', 6), ('Jordan', 'Jordan.png', 6), ('Kazakhstan', 'Kazakhstan.png', 6),
	('Kenya', 'Kenya.png', 6), ('Korea DPR', 'Korea_DPR.png', 6), ('Korea Republic', 'Korea_Republic.png', 6), ('Kosovo', 'Kosovo.png', 7),
	('Kuwait', 'Kuwait.png', 6), ('Kyrgyz Republic', 'Kyrgyz_Republic.png', 6), ('Laos', 'Laos.png', 6), ('Latvia', 'Latvia.png', 6),
	('Lebanon', 'Lebanon.png', 6), ('Lesotho', 'Lesotho.png', 6), ('Liberia', 'Liberia.png', 6), ('Libya', 'Libya.png', 6),
	('Liechtenstein', 'Liechtenstein.png', 6), ('Lithuania', 'Lithuania.png', 6), ('Luxembourg', 'Luxembourg.png', 6), ('Macau', 'Macau.png', 7),
	('Madagascar', 'Madagascar.png', 6), ('Malawi', 'Malawi.png', 6), ('Malaysia', 'Malaysia.png', 6), ('Maldives', 'Maldives.png', 6),
	('Mali', 'Mali.png', 6), ('Malta', 'Malta.png', 6), ('Mauritania', 'Mauritania.png', 6), ('Mauritius', 'Mauritius.png', 6),
	('Mexico', 'Mexico.png', 6), ('Moldova', 'Moldova.png', 6), ('Mongolia', 'Mongolia.png', 6), ('Montenegro', 'Montenegro.png', 6),
	('Montserrat', 'Montserrat.png', 7), ('Morocco', 'Morocco.png', 6), ('Mozambique', 'Mozambique.png', 6), ('Myanmar', 'Myanmar.png', 6),
	('Namibia', 'Namibia.png', 6), ('Nepal', 'Nepal.png', 6), ('Netherlands', 'Netherlands.png', 6), ('New Caledonia', 'New_Caledonia.png', 7),
	('New Zealand', 'New_Zealand.png', 6), ('Nicaragua', 'Nicaragua.png', 6), ('Niger', 'Niger.png', 6), ('Nigeria', 'Nigeria.png', 6),
	('Northern Ireland', 'Northern_Ireland.png', 6), ('Norway', 'Norway.png', 6), ('Oman', 'Oman.png', 6), ('Pakistan', 'Pakistan.png', 6),
	('Palestine', 'Palestine.png', 6), ('Panama', 'Panama.png', 6), ('Papua New Guinea', 'Papua_New_Guinea.png', 6), ('Paraguay', 'Paraguay.png', 6),
	('Peru', 'Peru.png', 6), ('Philippines', 'Philippines.png', 6), ('Poland', 'Poland.png', 6), ('Portugal', 'Portugal.png', 6),
	('Puerto Rico', 'Puerto_Rico.png', 7), ('Qatar', 'Qatar.png', 6), ('Republic of Ireland', 'Republic_of_Ireland.png', 6), ('Romania', 'Romania.png', 6),
	('Russia', 'Russia.png', 6), ('Rwanda', 'Rwanda.png', 6), ('Samoa', 'Samoa.png', 6), ('San Marino', 'San_Marino.png', 6),
	('São Tomé e Príncipe', 'São_Tomé_e_Príncipe.png', 6), ('Saudi Arabia', 'Saudi_Arabia.png', 6), ('Scotland', 'Scotland.png', 6), ('Senegal', 'Senegal.png', 6),
	('Serbia', 'Serbia.png', 6), ('Seychelles', 'Seychelles.png', 6), ('Sierra Leone', 'Sierra_Leone.png', 6), ('Singapore', 'Singapore.png', 6),
	('Slovakia', 'Slovakia.png', 6), ('Slovenia', 'Slovenia.png', 6), ('Solomon Islands', 'Solomon_Islands.png', 6), ('Somalia', 'Somalia.png', 6), ('South Africa', 'South_Africa.png', 6),
	('South Sudan', 'South_Sudan.png', 6), ('Spain', 'Spain.png', 6), ('Sri Lanka', 'Sri_Lanka.png', 6), ('St. Kitts and Nevis', 'St._Kitts_and_Nevis.png', 6),
	('St. Lucia', 'St._Lucia.png', 6), ('St. Vincent and the Grenadines', 'St._Vincent_and_the_Grenadines.png', 6), ('Sudan', 'Sudan.png', 6), ('Suriname', 'Suriname.png', 6),
	('Swaziland', 'Swaziland.png', 6), ('Sweden', 'Sweden.png', 6), ('Switzerland', 'Switzerland.png', 6), ('Syria', 'Syria.png', 6),
	('Tahiti', 'Tahiti.png', 6), ('Tajikistan', 'Tajikistan.png', 6), ('Tanzania', 'Tanzania.png', 6), ('Thailand', 'Thailand.png', 6),
	('Timor-Leste', 'Timor-Leste.png', 6), ('Togo', 'Togo.png', 6), ('Tonga', 'Tonga.png', 6), ('Trinidad and Tobago', 'Trinidad_and_Tobago.png', 6), ('Tunisia', 'Tunisia.png', 6),
	('Turkey', 'Turkey.png', 6), ('Turkmenistan', 'Turkmenistan.png', 6), ('Turks and Caicos Islands', 'Turks_and_Caicos_Islands.png', 7), ('Uganda', 'Uganda.png', 6),
	('Ukraine', 'Ukraine.png', 6), ('United Arab Emirates', 'United_Arab_Emirates.png', 6), ('Uruguay', 'Uruguay.png', 6), ('US Virgin Islands', 'US_Virgin_Islands.png', 7),
	('USA', 'USA.png', 6), ('Uzbekistan', 'Uzbekistan.png', 6), ('Vanuatu', 'Vanuatu.png', 6), ('Venezuela', 'Venezuela.png', 6),
	('Vietnam', 'Vietnam.png', 6), ('Wales', 'Wales.png', 6), ('Yemen', 'Yemen.png', 6), ('Zambia', 'Zambia.png', 6),
	('Zimbabwe', 'Zimbabwe.png', 6);
